[build]
  base = "/"
  publish = "templates"
  command = "pip install -r requirements.txt && python -c 'import app; app.app.run()'"
  node_version = false
  node = false
  npm = false
  yarn = false
  npm_ci = false
  functions = false
  plugins = []

[build.environment]
  FLASK_ENV = "production"
  DATABASE_URL = "sqlite:///instance/commissary.db"
  SECRET_KEY = "${SECRET_KEY:-your-secret-key-here}"
