[build]
  base = "/"
  publish = "templates"
  command = "pip install -r requirements.txt"

[build.environment]
  FLASK_ENV = "production"
  DATABASE_URL = "sqlite:///instance/commissary.db"
  SECRET_KEY = "${SECRET_KEY:-your-secret-key-here}"

# Configure Netlify to use Python
[build]
  command = "pip install -r requirements.txt"
  publish = "templates"
  base = "/"

# Disable Node.js build processing
[build]
  node_version = false

# Add Python-specific build settings
[build]
  command = "pip install -r requirements.txt && python -c 'import app; app.app.run()'"
  publish = "templates"
  base = "/"

# Remove any default Netlify settings
[build]
  functions = false
  plugins = []
  node = false
  npm = false
  yarn = false
  npm_ci = false
