[build]
  base = "/"
  publish = "templates"
  command = "pip install -r requirements.txt"

[functions]
  [functions.node_version]
    version = "18"

[build.environment]
  FLASK_ENV = "production"
  DATABASE_URL = "sqlite:///instance/commissary.db"
