[build]
  base = "/"
  publish = "templates"
  command = "python -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
  context = "production"

[build.environment]
  FLASK_ENV = "production"
  DATABASE_URL = "sqlite:///instance/commissary.db"
  SECRET_KEY = "${SECRET_KEY:-your-secret-key-here}"

[functions]
  python = true
  python_version = "3.10"

[functions.build]
  command = "pip install -r requirements.txt"
  publish = "templates"
  base = "/"
