[build]
  base = "/"
  publish = "templates"
  command = "pip install -r requirements.txt"
  context = "production"
  python = true
  python_version = "3.10"
  venv = true

[build.environment]
  FLASK_ENV = "production"
  DATABASE_URL = "sqlite:///instance/commissary.db"
  SECRET_KEY = "${SECRET_KEY:-your-secret-key-here}"
