[build]
  base = "/"
  publish = "templates"
  command = "pip install -r requirements.txt"

[build.environment]
  FLASK_ENV = "production"
  DATABASE_URL = "sqlite:///instance/commissary.db"
  SECRET_KEY = "${SECRET_KEY:-your-secret-key-here}"

# Python-specific configuration
[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "templates"
  base = "/"

# Disable Netlify's Node.js build processing
[build]
  node_version = false
