[build]
  base = "/"
  publish = "templates"
  command = "pip install -r requirements.txt"
  node = false
  npm = false
  yarn = false
  npm_ci = false
  functions = false
  plugins = []
  python_version = "3.11"
  python = true
  venv = true
  context = "production"
  framework = "flask"
  build_command = "pip install -r requirements.txt"
  publish_dir = "templates"
  base_directory = "/"

[build.environment]
  FLASK_ENV = "production"
  DATABASE_URL = "sqlite:///instance/commissary.db"
  SECRET_KEY = "${SECRET_KEY:-your-secret-key-here}"
